# Generated by Django 4.1.5 on 2023-01-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=128, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_casa', models.PositiveSmallIntegerField(verbose_name='Numero da Casa')),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do Veículo')),
                ('horario_chegada', models.DateTimeField(auto_now_add=True, verbose_name='Horario de entrada na portaria')),
                ('horario_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horario de saída na portaria')),
                ('horario_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Horario de autorização de entrada')),
                ('morador_responsavel', models.CharField(blank=True, max_length=128, verbose_name='Morador responsável pela autorização')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porteiros.porteiro', verbose_name='Porteiro responsável pelo registro')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
